name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest

      - name: Build Docker image (smoke)
        run: docker build -t email-ingestor:ci .

      - name: Run smoke tests inside container
        run: docker run --rm email-ingestor:ci pytest
